---

- name: Run show commands on routers
  hosts: cisco_routers
  gather_facts: false

  tasks:

     - name: sh ip os da ro
       ios_command:
         commands: show ip ospf database router
       register: sh_ip_os_da_ro

     - name: sh ip os da ne
       ios_command:
         commands: show ip ospf database network
       register: sh_ip_os_da_ne

     - name: sh ip os da ext
       ios_command:
         commands: show ip ospf database external
       register: sh_ip_os_da_ext

     - name: display output
       debug:
         var=sh_ip_os_da_ro.stdout

     - name: display output
       debug:
         var=sh_ip_os_da_ne.stdout

     - name: display output
       debug:
         var=sh_ip_os_da_ext.stdout


#    - name: run sh ip arp
#      ios_command:
#        commands: sh ip arp


#- name: Run command on R1
#  hosts: 192.168.100.1
#  gather_facts: false

#  tasks:

#    - name: run sh int status
#      ios_command:
#        commands: sh clock
